"use client";

// ═══════════════════════════════════════════════════════════════════════════
// app/acquiflow-intel/[dealId]/page.tsx
//
// AcquiFlow — Institutional Read (parallel intelligence surface)
//
// READ-ONLY by design. This surface consumes /api/deals/[id]/summary and
// renders CP's ACTUAL categorical output as an underwriting review. It performs
// NO mutations: no forms, no save handlers, no writes, no uploads, no
// onboarding, no imports from the operational /buyer-dashboard. It is
// architecturally isolated and presentation-first.
//
// STRUCTURE-FIRST: every word on screen is derived deterministically from the
// engine's real fields (classification, contributing_factors, persona counts,
// ranked items). The posture sentence is assembled from a fixed template — NOT
// generated by an LLM. The committee-style narrative layer is a SEPARATE future
// route and is intentionally absent here.
//
// Design discipline: no score, no gauge, no traffic light, no overall rating,
// no red/yellow/green simplification. Show the SHAPE of the judgment.
// ═══════════════════════════════════════════════════════════════════════════

import { useEffect, useState, type ReactNode } from "react";
import { authedGet } from "../_lib/authedFetch";


// ── Design tokens (institutional editorial) ──────────────────────────────────
const C = {
  ink: "#1a1d23", inkSoft: "#3d434e", faint: "#6b7280",
  paper: "#f4f1ea", card: "#fdfcfa", rule: "#d8d3c7", ruleSoft: "#e8e3d8",
  accent: "#2d4a3e", accentSoft: "#5a7464",
  binding: "#8a4b2d", engaged: "#2d4a3e", blocking: "#6b3a4a", cautious: "#9c7c3a",
};
const serif = "'Hoefler Text','Iowan Old Style','Palatino Linotype',Georgia,serif";
const sans = "'Helvetica Neue','Inter',system-ui,sans-serif";

// ── Deterministic humanizers — turn CP field tokens into readable labels ─────
// These are fixed lookups, not interpretation. Unknown tokens fall back to a
// title-cased version of the raw token so nothing is hidden or invented.
function humanizeToken(token: string): string {
  if (!token) return "";
  const map: Record<string, string> = {
    durability_score: "Durability",
    seller_note: "Seller-note structure",
    structural_concern: "Structural concern",
    conventional_bank: "Conventional financing",
    sba: "SBA financing",
    cashflow: "Cash flow",
    evidence: "Evidence quality",
    financial: "Financial profile",
  };
  if (map[token]) return map[token];
  return token
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function humanizeState(state: string): string {
  const map: Record<string, string> = {
    dominant_constraint: "Binding constraint",
    highest_fragility: "Highest fragility",
    interested: "Engaged",
    blocking: "Blocking",
    cautious: "Cautious",
    declined: "Declined",
  };
  return map[state] ?? humanizeToken(state);
}

function classificationLabel(c: string): string {
  const map: Record<string, string> = {
    structurally_blocked: "Structurally blocked",
    evidence_insufficient: "Evidence insufficient",
    decision_ready: "Decision ready",
    decision_ready_with_caveats: "Decision ready, with caveats",
    all_paths_declined: "All paths declined",
  };
  return map[c] ?? humanizeToken(c);
}

// Humanize a ranked item: prefer the engine's item_label; else derive from id.
function itemLabel(item: { item_label?: string | null; item_id: string; item_kind: string }): string {
  if (item.item_label && item.item_label.trim().length > 0) return item.item_label;
  // Derive a readable label from structured comfort/discomfort ids.
  const id = item.item_id;
  const tail = id.split(".").slice(-1)[0] ?? id;
  const kind = item.item_kind.replace(/_/g, " ");
  return `${humanizeToken(tail)} — ${kind}`;
}

const toneForState = (state: string) =>
  state === "dominant_constraint" || state === "highest_fragility"
    ? C.binding
    : state === "blocking"
    ? C.blocking
    : state === "interested"
    ? C.engaged
    : C.cautious;

// ── Deterministic posture synthesis (template — NOT an LLM) ──────────────────
function synthesizePosture(readiness: any): string {
  const cls = classificationLabel(readiness.classification).toLowerCase();
  const i = readiness.interested_personality_count ?? 0;
  const c = readiness.cautious_personality_count ?? 0;
  const d = readiness.declined_personality_count ?? 0;
  const total = i + c + d;

  // Binding factor = first contributing factor flagged as dominant_constraint,
  // else the first contributing factor.
  const factors = readiness.contributing_factors ?? [];
  const binding =
    factors.find((f: any) => f.state === "dominant_constraint") ?? factors[0] ?? null;
  const bindingName = binding ? humanizeToken(binding.axis_or_dimension).toLowerCase() : null;

  const spread =
    total > 0
      ? `Of ${total} capital structure${total === 1 ? "" : "s"} evaluated, ` +
        `${i} would engage, ${c} ${c === 1 ? "is" : "are"} cautious, and ${d} would decline.`
      : "";

  const bindingClause = bindingName
    ? ` The binding question is ${bindingName} — not valuation.`
    : "";

  return `This deal is ${cls}.${spread ? " " + spread : ""}${bindingClause}`.trim();
}

// ── Provenance affordance ────────────────────────────────────────────────────
function Why({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false);
  return (
    <span style={{ position: "relative", display: "inline-block" }}>
      <button
        onClick={() => setOpen((o) => !o)}
        style={{
          marginLeft: 8, fontSize: 9.5, letterSpacing: "0.1em", textTransform: "uppercase",
          color: C.accentSoft, background: "none", border: `1px solid ${C.rule}`, borderRadius: 2,
          padding: "1px 6px", cursor: "pointer", fontFamily: sans, verticalAlign: "middle",
        }}
      >
        why
      </button>
      {open && (
        <span
          style={{
            position: "absolute", top: "calc(100% + 6px)", left: 0, zIndex: 30, width: 300,
            background: C.ink, color: C.paper, padding: "11px 13px", borderRadius: 4,
            fontSize: 12.5, lineHeight: 1.55, fontWeight: 400, fontFamily: sans,
            boxShadow: "0 10px 30px rgba(0,0,0,0.25)", letterSpacing: 0, textTransform: "none",
          }}
        >
          {children}
        </span>
      )}
    </span>
  );
}

function Header({ children, sub }: { children: ReactNode; sub?: boolean }) {
  return (
    <div
      style={{
        fontFamily: sans, fontSize: sub ? 10.5 : 11, letterSpacing: "0.14em",
        textTransform: "uppercase", color: sub ? C.accentSoft : C.faint,
        fontWeight: 600, marginBottom: sub ? 6 : 14,
      }}
    >
      {children}
    </div>
  );
}

// ── Main page ────────────────────────────────────────────────────────────────
export default function IntelDealPage({ params }: { params: { dealId: string } }) {
  const dealId = params.dealId;
  const [state, setState] = useState<
    { status: "loading" } |
    { status: "error"; kind: string; reason: string } |
    { status: "ok"; data: any; manifestId: string; generatedAt: string }
  >({ status: "loading" });

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        // Resilient read: handles token shape, expiry, and one refresh-retry.
        const json = await authedGet(`/api/deals/${dealId}/summary`);
        if (cancelled) return;
        if (!json.success) {
          setState({ status: "error", kind: json.error_kind ?? "unknown", reason: json.reason ?? "Unable to load institutional read." });
        } else {
          setState({ status: "ok", data: json.data, manifestId: json.manifest_id, generatedAt: json.generated_at });
        }
      } catch (e) {
        if (!cancelled) setState({ status: "error", kind: "network", reason: e instanceof Error ? e.message : String(e) });
      }
    })();
    return () => { cancelled = true; };
  }, [dealId]);

  return (
    <div style={{ background: C.paper, minHeight: "100vh", paddingBottom: 80, color: C.ink }}>
      <Masthead dealId={dealId} />
      <div style={{ maxWidth: 1080, margin: "0 auto", padding: "40px 40px 0" }}>
        {state.status === "loading" && <Loading />}
        {state.status === "error" && <ErrorView kind={state.kind} reason={state.reason} />}
        {state.status === "ok" && <Review data={state.data} manifestId={state.manifestId} generatedAt={state.generatedAt} />}
      </div>
    </div>
  );
}

function Masthead({ dealId }: { dealId: string }) {
  return (
    <div style={{ borderBottom: `1px solid ${C.rule}`, background: C.card }}>
      <div style={{ maxWidth: 1080, margin: "0 auto", padding: "26px 40px" }}>
        <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
          <div>
            <div style={{ fontFamily: serif, fontSize: 26, letterSpacing: "0.01em" }}>
              AcquiFlow
              <span style={{ fontFamily: sans, fontSize: 11, letterSpacing: "0.16em", textTransform: "uppercase", color: C.accentSoft, marginLeft: 14, fontWeight: 600 }}>
                Institutional Read
              </span>
            </div>
            <div style={{ fontFamily: serif, fontSize: 13.5, fontStyle: "italic", color: C.faint, marginTop: 4 }}>
              Pre-LOI underwriting intelligence · read-only review surface
            </div>
          </div>
          <a href="/acquiflow-intel" style={{ fontFamily: sans, fontSize: 11.5, color: C.accent, textDecoration: "none", letterSpacing: "0.04em", borderBottom: `1px solid ${C.rule}`, paddingBottom: 2 }}>
            ← All reviews
          </a>
        </div>
      </div>
    </div>
  );
}

function Loading() {
  return <div style={{ fontFamily: serif, fontSize: 16, fontStyle: "italic", color: C.faint, padding: "40px 0" }}>Preparing the institutional read…</div>;
}

function ErrorView({ kind, reason }: { kind: string; reason: string }) {
  const friendly =
    kind === "snapshot_not_found" ? "This deal has no institutional read yet."
    : kind === "auth_token_missing" || kind === "unauthenticated" ? "Please sign in to view this review."
    : kind === "rls_access_denied" ? "You don't have access to this deal."
    : kind === "deal_not_found" ? "No deal exists at this address."
    : "This review could not be loaded.";
  return (
    <div style={{ borderLeft: `3px solid ${C.blocking}`, paddingLeft: 22, padding: "20px 0 20px 22px" }}>
      <Header>Unable to load</Header>
      <div style={{ fontFamily: serif, fontSize: 19, lineHeight: 1.5 }}>{friendly}</div>
      <div style={{ fontFamily: sans, fontSize: 12, color: C.faint, marginTop: 10 }}>{kind} · {reason}</div>
    </div>
  );
}

// ── The review itself ─────────────────────────────────────────────────────────
function Review({ data, manifestId, generatedAt }: { data: any; manifestId: string; generatedAt: string }) {
  const readiness = data.readiness ?? {};
  const impact = data.impact_ranking ?? {};
  const factors = readiness.contributing_factors ?? [];
  const ranked = impact.ranked_items ?? [];
  const posture = synthesizePosture(readiness);

  // Split ranked items into a diligence path: binding-constraint items first.
  const bindingItems = ranked.filter((r: any) => r.impact_dimensions?.affects_binding_constraint);
  const otherItems = ranked.filter((r: any) => !r.impact_dimensions?.affects_binding_constraint);

  const i = readiness.interested_personality_count ?? 0;
  const c = readiness.cautious_personality_count ?? 0;
  const d = readiness.declined_personality_count ?? 0;

  return (
    <div>
      {/* Move 1 — posture sentence */}
      <div style={{ borderLeft: `3px solid ${C.binding}`, paddingLeft: 22, marginBottom: 38 }}>
        <Header>Underwriting posture</Header>
        <div style={{ fontFamily: serif, fontSize: 22, lineHeight: 1.5 }}>
          {posture}
          <Why>
            Assembled deterministically from the engine's readiness classification, capital-structure
            posture counts, and the binding contributing factor. Fixed template — not generated prose.
            Snapshot {data.snapshot_id}.
          </Why>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 44 }}>
        {/* Move 2 — constraint stack */}
        <div>
          <Header>Structure of the read</Header>
          {factors.length === 0 && <Empty>No contributing factors recorded for this snapshot.</Empty>}
          {factors.map((f: any, idx: number) => (
            <div key={idx} style={{ display: "flex", gap: 16, padding: "15px 0", borderTop: idx === 0 ? "none" : `1px solid ${C.ruleSoft}` }}>
              <div style={{ flexShrink: 0, width: 124 }}>
                <div style={{ fontFamily: sans, fontSize: 10, letterSpacing: "0.12em", textTransform: "uppercase", color: toneForState(f.state), fontWeight: 600 }}>
                  {humanizeState(f.state)}
                </div>
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ display: "flex", alignItems: "baseline", gap: 10 }}>
                  <span style={{ fontFamily: serif, fontSize: 16.5 }}>{humanizeToken(f.axis_or_dimension)}</span>
                  {f.band && <span style={{ fontFamily: sans, fontSize: 11, color: C.faint }}>{f.band} band</span>}
                </div>
              </div>
              <div style={{ flexShrink: 0, width: 12, paddingTop: 5 }}>
                <div style={{ width: 9, height: 9, borderRadius: "50%", background: toneForState(f.state), opacity: f.state === "interested" ? 0.5 : 1 }} />
              </div>
            </div>
          ))}
        </div>

        {/* Move 3 — capital-structure distribution (real counts, NOT named) */}
        <div>
          <Header>
            How capital structures see it
            <Why>
              The engine simulates each financing structure independently and reports a categorical
              stance — it never blends them into one verdict. This snapshot reports the distribution of
              stances; individual structure identities are part of the deeper read.
            </Why>
          </Header>
          <StanceDistribution interested={i} cautious={c} declined={d} />
          <div style={{ fontFamily: serif, fontSize: 14, lineHeight: 1.55, color: C.inkSoft, marginTop: 16 }}>
            {d > 0 && i > 0
              ? "The structures disagree — which is the point. A deal that some structures engage and others decline is not a single verdict; it is a question of which capital structure it fits."
              : i > 0
              ? "Multiple structures would engage at this stage, subject to the diligence path below."
              : "No structure engages cleanly at this stage; the binding constraint must be resolved first."}
          </div>
        </div>
      </div>

      {/* Move 4 — diligence path */}
      <div style={{ marginTop: 42, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 44 }}>
        <div>
          <Header>
            Diligence path
            <Why>
              The engine's impact ranking, ordered so that items on the binding constraint come first.
              Resolving these is what moves the read — and what makes a later quality-of-earnings review
              targeted rather than exploratory.
            </Why>
          </Header>
          {bindingItems.length > 0 && (
            <div style={{ marginBottom: 18 }}>
              <Header sub>Resolve the binding constraint first</Header>
              {bindingItems.map((it: any, idx: number) => <DiligenceItem key={idx} it={it} critical />)}
            </div>
          )}
          {otherItems.length > 0 && (
            <div>
              <Header sub>Strengthen the evidence base</Header>
              {otherItems.slice(0, 6).map((it: any, idx: number) => <DiligenceItem key={idx} it={it} />)}
            </div>
          )}
          {ranked.length === 0 && <Empty>No ranked diligence items for this snapshot.</Empty>}
        </div>

        {/* What this is / is not */}
        <div>
          <Header>What this is — and is not</Header>
          <div style={{ fontFamily: serif, fontSize: 14.5, lineHeight: 1.65, color: C.inkSoft }}>
            This is a <strong>pre-LOI underwriting read</strong> — what a lender, investment committee, or
            experienced acquirer would question before you commit. It is not a valuation, not a score, and
            not a substitute for quality-of-earnings or lender underwriting. It tells you what those
            processes are likely to scrutinize, so you can decide where to spend time and capital.
          </div>
          <div style={{ marginTop: 20, fontFamily: sans, fontSize: 11.5, color: C.faint, lineHeight: 1.7 }}>
            <DistRow label="High-impact items" value={impact.high_count ?? 0} />
            <DistRow label="Moderate" value={impact.moderate_count ?? 0} />
            <DistRow label="Low" value={impact.low_count ?? 0} />
            <DistRow label="Blocking structural concerns" value={readiness.blocking_structural_concern_count ?? 0} />
            <DistRow label="Evidence gaps" value={readiness.missing_evidence_count ?? 0} />
          </div>
        </div>
      </div>

      {/* Provenance footer */}
      <div style={{ marginTop: 56, borderTop: `1px solid ${C.rule}`, paddingTop: 16, fontFamily: serif, fontSize: 12.5, fontStyle: "italic", color: C.faint, lineHeight: 1.6 }}>
        Deterministic engine · manifest {manifestId} · generated {new Date(generatedAt).toLocaleString()}.
        Every element above derives from a rule, threshold, or evidence band. This surface is read-only;
        it does not alter the deal.
      </div>
    </div>
  );
}

function StanceDistribution({ interested, cautious, declined }: { interested: number; cautious: number; declined: number }) {
  const rows = [
    { label: "Would engage", n: interested, color: C.engaged },
    { label: "Cautious", n: cautious, color: C.cautious },
    { label: "Would decline", n: declined, color: C.blocking },
  ];
  const total = interested + cautious + declined || 1;
  return (
    <div style={{ border: `1px solid ${C.ruleSoft}`, background: C.card }}>
      {rows.map((r, idx) => (
        <div key={idx} style={{ display: "flex", alignItems: "center", gap: 14, padding: "14px 18px", borderTop: idx === 0 ? "none" : `1px solid ${C.ruleSoft}` }}>
          <div style={{ width: 96, fontFamily: sans, fontSize: 10.5, letterSpacing: "0.08em", textTransform: "uppercase", color: r.color, fontWeight: 600 }}>{r.label}</div>
          <div style={{ flex: 1, height: 6, background: C.ruleSoft, position: "relative" }}>
            <div style={{ position: "absolute", left: 0, top: 0, bottom: 0, width: `${(r.n / total) * 100}%`, background: r.color, opacity: 0.85 }} />
          </div>
          <div style={{ width: 18, textAlign: "right", fontFamily: serif, fontSize: 18 }}>{r.n}</div>
        </div>
      ))}
    </div>
  );
}

function DiligenceItem({ it, critical }: { it: any; critical?: boolean }) {
  const dims = it.impact_dimensions ?? {};
  const onNode = dims.is_on_critical_fragility_node;
  return (
    <div style={{ display: "flex", gap: 12, padding: "11px 0", borderTop: `1px solid ${C.ruleSoft}` }}>
      <div style={{ flexShrink: 0, marginTop: 4 }}>
        <div style={{ width: 7, height: 7, borderRadius: critical ? 0 : "50%", background: critical ? C.binding : C.accentSoft, transform: critical ? "rotate(45deg)" : "none" }} />
      </div>
      <div>
        <div style={{ fontFamily: sans, fontSize: 13.5, fontWeight: 500, lineHeight: 1.4 }}>{itemLabel(it)}</div>
        <div style={{ fontFamily: sans, fontSize: 10.5, color: C.faint, marginTop: 4, letterSpacing: "0.03em" }}>
          {it.impact_classification?.toUpperCase()}
          {onNode && " · on critical fragility node"}
          {dims.affects_binding_constraint && " · affects binding constraint"}
        </div>
      </div>
    </div>
  );
}

function DistRow({ label, value }: { label: string; value: number }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", padding: "3px 0", borderBottom: `1px solid ${C.ruleSoft}` }}>
      <span>{label}</span>
      <span style={{ fontFamily: serif, fontSize: 14, color: C.ink }}>{value}</span>
    </div>
  );
}

function Empty({ children }: { children: ReactNode }) {
  return <div style={{ fontFamily: serif, fontSize: 14, fontStyle: "italic", color: C.faint, padding: "12px 0" }}>{children}</div>;
}
