// lib/investigationChecklist.ts
// E4 Phase 3 — Deterministic investigation item generation (template_version v2.0)
//
// D4 rules (locked):
//   - Items are generated by deterministic triggers ONLY. No LLM adds,
//     removes, or rewords an item. Sonnet may NARRATE items in the memo
//     but never alters the set.
//   - Every item text begins with an action verb. Status/policy statements
//     are NOT checklist items (they live in verification status rendering).
//   - Cumulative bands: HIGH includes MODERATE's items; EXTREME includes both.
//   - low_margin_flag adds items but never touches the confidence grade.
//
// Pure function. No I/O. Never throws.

import type { DivergenceBand, ReferenceQuality } from "@/lib/investigationEngine";

export interface InvestigationItem {
  item_key: string;
  trigger: string;           // which rule produced it
  template_version: "v2.0";
  priority: 1 | 2 | 3;       // 1 = highest
  text: string;
}

export interface ChecklistInputs {
  divergenceBand: DivergenceBand | null;
  referenceQuality: ReferenceQuality | null;
  closedLensBand: DivergenceBand | null;
  lowMarginFlag: boolean;
  referenceN: number | null;
}

const BAND_ORDER: DivergenceBand[] = ["LOW", "MODERATE", "HIGH", "EXTREME"];
const V = "v2.0" as const;

export function generateInvestigationItems(inp: ChecklistInputs): InvestigationItem[] {
  const items: InvestigationItem[] = [];
  const band = inp.divergenceBand;
  if (!band) return items; // observation skipped → no divergence-driven items

  const rank = BAND_ORDER.indexOf(band);

  // MODERATE and above
  if (rank >= 1) {
    items.push(
      { item_key: "obtain_pnl_addbacks", trigger: "band_moderate", template_version: V, priority: 2,
        text: "Obtain the current P&L and an itemized add-back schedule with supporting documents." },
      { item_key: "reconcile_sde_schedule", trigger: "band_moderate", template_version: V, priority: 2,
        text: "Reconcile reported SDE to the add-back schedule line by line." },
    );
  }
  // HIGH and above
  if (rank >= 2) {
    items.push(
      { item_key: "obtain_tax_returns", trigger: "band_high", template_version: V, priority: 1,
        text: "Obtain three years of business tax returns." },
      { item_key: "reconcile_sde_returns", trigger: "band_high", template_version: V, priority: 1,
        text: "Reconcile reported SDE to filed returns; identify and document every variance." },
      { item_key: "document_owner_comp", trigger: "band_high", template_version: V, priority: 2,
        text: "Document owner compensation and the market cost of a replacement operator." },
    );
  }
  // EXTREME
  if (rank >= 3) {
    items.push(
      { item_key: "explain_margin_outlier", trigger: "band_extreme", template_version: V, priority: 1,
        text: "Explain the business model responsible for the margin outlier relative to category peers." },
      { item_key: "docs_before_reliance", trigger: "band_extreme", template_version: V, priority: 1,
        text: "Obtain seller documentation sufficient to support stated earnings before relying on them in valuation or financing." },
    );
  }

  // Lens disagreement (> 1 band between listing and closed lenses)
  if (
    inp.closedLensBand !== null &&
    Math.abs(rank - BAND_ORDER.indexOf(inp.closedLensBand)) > 1
  ) {
    items.push(
      { item_key: "confirm_closed_evidence", trigger: "lens_disagreement", template_version: V, priority: 1,
        text: "Confirm pricing expectations against closed-transaction evidence for this category." },
      { item_key: "obtain_broker_comps", trigger: "lens_disagreement", template_version: V, priority: 2,
        text: "Obtain the broker's comparable-sale support for the asking price." },
    );
  }

  // Low margin (distinct signal; never affects the grade)
  if (inp.lowMarginFlag) {
    items.push(
      { item_key: "verify_low_margin", trigger: "low_margin_flag", template_version: V, priority: 2,
        text: "Verify expense load, owner compensation treatment, and any non-recurring costs suppressing the reported margin." },
    );
  }

  // Thin reference (quality C)
  if (inp.referenceQuality === "C") {
    items.push(
      { item_key: "corroborate_benchmarks", trigger: "quality_c", template_version: V, priority: 3,
        text: `Corroborate benchmark context independently; the reference set for this category is directional only${inp.referenceN ? ` (${inp.referenceN} peers)` : ""}.` },
    );
  }

  // De-dup by item_key (defensive) and sort by priority then key for stable output
  const seen = new Set<string>();
  return items
    .filter((i) => (seen.has(i.item_key) ? false : (seen.add(i.item_key), true)))
    .sort((a, b) => a.priority - b.priority || a.item_key.localeCompare(b.item_key));
}
