import { CategoryMapping } from "@/types/marketview";

// ===========================================
// Business Category → API Query Mappings
// ===========================================
// Each category maps to the correct Google Places types,
// Yelp categories, and industry-specific revenue multipliers.
//
// Original: 20 categories
// Added:    23 categories covering remaining NexTax industries
// Total:    43 categories

export const CATEGORY_MAPPINGS: Record<string, CategoryMapping> = {

  // ─── ORIGINAL 20 (unchanged) ─────────────────────────────────────────────

  "Fitness / Gym": {
    label: "Fitness / Gym",
    googleTypes: ["gym", "health"],
    yelpCategories: ["gyms", "fitness", "boot_camps", "yoga", "pilates", "martialarts"],
    keywords: ["gym", "fitness", "crossfit", "workout", "training"],
    revenueMultiplier: 1800,
    franchiseKeywords: ["Planet Fitness", "Anytime Fitness", "Orangetheory", "F45", "Crunch", "Gold's Gym", "LA Fitness", "24 Hour", "Snap Fitness", "Burn Boot Camp"],
  },
  "Restaurant / Fast Casual": {
    label: "Restaurant / Fast Casual",
    googleTypes: ["restaurant"],
    yelpCategories: ["restaurants", "food", "fastfood", "newamerican", "tradamerican"],
    keywords: ["restaurant", "grill", "kitchen", "eatery", "dining"],
    revenueMultiplier: 1200,
    franchiseKeywords: ["Chipotle", "Panera", "Chick-fil-A", "Five Guys", "Wingstop", "Jersey Mike", "Sweetgreen", "Shake Shack", "Cava", "Noodles"],
  },
  "Coffee Shop / Cafe": {
    label: "Coffee Shop / Cafe",
    googleTypes: ["cafe"],
    yelpCategories: ["coffee", "coffeeroasteries", "coffeeshops", "bubbletea", "tea"],
    keywords: ["coffee", "cafe", "espresso", "roast", "brew"],
    revenueMultiplier: 800,
    franchiseKeywords: ["Starbucks", "Dunkin", "Peet's", "Dutch Bros", "Caribou", "Tim Hortons", "Scooter's", "Biggby"],
  },
  "Auto Repair / Service": {
    label: "Auto Repair / Service",
    googleTypes: ["car_repair"],
    yelpCategories: ["autorepair", "oilchange", "tires", "transmission_repair", "auto_detailing"],
    keywords: ["auto repair", "mechanic", "car service", "oil change", "brake"],
    revenueMultiplier: 2200,
    franchiseKeywords: ["Midas", "Jiffy Lube", "Meineke", "Maaco", "Firestone", "Pep Boys", "Valvoline", "Take 5", "Christian Brothers"],
  },
  "Dental Practice": {
    label: "Dental Practice",
    googleTypes: ["dentist"],
    yelpCategories: ["dentists", "cosmetic_dentists", "pediatric_dentists", "orthodontists", "endodontists"],
    keywords: ["dental", "dentist", "orthodont", "oral", "teeth"],
    revenueMultiplier: 3500,
    franchiseKeywords: ["Aspen Dental", "Heartland", "Pacific Dental", "Gentle Dental", "Western Dental", "Comfort Dental", "Ideal Dental"],
  },
  "Med Spa / Aesthetics": {
    label: "Med Spa / Aesthetics",
    googleTypes: ["spa", "beauty_salon"],
    yelpCategories: ["medspas", "skincare", "laser_hair_removal", "permanentmakeup"],
    keywords: ["med spa", "medspa", "aesthetics", "botox", "laser", "injectable"],
    revenueMultiplier: 2800,
    franchiseKeywords: ["Ideal Image", "LaserAway", "SkinSpirit", "Skin Laundry", "Radiance", "Sono Bello"],
  },
  "Hair Salon / Barbershop": {
    label: "Hair Salon / Barbershop",
    googleTypes: ["hair_care", "beauty_salon"],
    yelpCategories: ["hair", "hairstylists", "barbers", "blowoutservices", "hair_extensions"],
    keywords: ["salon", "barber", "hair", "cuts", "style", "color"],
    revenueMultiplier: 900,
    franchiseKeywords: ["Great Clips", "Supercuts", "Sport Clips", "Floyd's", "Roosters", "Cost Cutters", "Fantastic Sams"],
  },
  "Childcare / Daycare": {
    label: "Childcare / Daycare",
    googleTypes: ["school"],
    yelpCategories: ["childcare", "preschools", "montessori"],
    keywords: ["daycare", "childcare", "preschool", "montessori", "learning center", "child care"],
    revenueMultiplier: 2500,
    franchiseKeywords: ["KinderCare", "Bright Horizons", "Goddard School", "Primrose", "Kiddie Academy", "Children of America", "Lightbridge"],
  },
  "Pet Services / Grooming": {
    label: "Pet Services / Grooming",
    googleTypes: ["pet_store", "veterinary_care"],
    yelpCategories: ["groomer", "pet_sitting", "pet_boarding", "dog_walkers", "pet_training"],
    keywords: ["pet", "grooming", "dog", "boarding", "daycare pet"],
    revenueMultiplier: 1100,
    franchiseKeywords: ["PetSmart", "Petco", "Camp Bow Wow", "Dogtopia", "Scenthound", "Wag N' Wash"],
  },
  "Cleaning / Janitorial": {
    label: "Cleaning / Janitorial",
    googleTypes: ["home_goods_store"],
    yelpCategories: ["home_cleaning", "office_cleaning", "carpetcleaning", "window_washing"],
    keywords: ["cleaning", "janitorial", "maid", "housekeeping"],
    revenueMultiplier: 1500,
    franchiseKeywords: ["Molly Maid", "Merry Maids", "Jan-Pro", "ServiceMaster", "Chem-Dry", "Stanley Steemer", "The Maids"],
  },
  "HVAC / Plumbing": {
    label: "HVAC / Plumbing",
    googleTypes: ["plumber", "electrician"],
    yelpCategories: ["hvac", "plumbing", "heating", "air_conditioning"],
    keywords: ["hvac", "plumbing", "heating", "cooling", "air conditioning"],
    revenueMultiplier: 2800,
    franchiseKeywords: ["One Hour Heating", "Mr. Rooter", "Roto-Rooter", "Benjamin Franklin", "Aire Serv", "ARS Rescue Rooter"],
  },
  "Accounting / Tax Services": {
    label: "Accounting / Tax Services",
    googleTypes: ["accounting"],
    yelpCategories: ["accountants", "tax_services", "bookkeepers", "payroll_services"],
    keywords: ["accounting", "tax", "CPA", "bookkeeping", "payroll"],
    revenueMultiplier: 3000,
    franchiseKeywords: ["H&R Block", "Jackson Hewitt", "Liberty Tax", "Padgett Business Services"],
  },
  "Physical Therapy / Chiropractic": {
    label: "Physical Therapy / Chiropractic",
    googleTypes: ["physiotherapist", "doctor"],
    yelpCategories: ["physicaltherapy", "chiropractors", "sports_medicine", "acupuncture"],
    keywords: ["physical therapy", "chiropract", "rehab", "sports medicine"],
    revenueMultiplier: 2400,
    franchiseKeywords: ["ATI Physical Therapy", "CORA", "Athletico", "US Physical Therapy", "The Joint"],
  },
  "Quick Service Restaurant (QSR)": {
    label: "Quick Service Restaurant (QSR)",
    googleTypes: ["restaurant", "meal_takeaway"],
    yelpCategories: ["hotdogs", "burgers", "pizza", "sandwiches", "chicken_wings", "mexican"],
    keywords: ["fast food", "drive thru", "quick service", "takeout"],
    revenueMultiplier: 1400,
    franchiseKeywords: ["McDonald's", "Burger King", "Wendy's", "Taco Bell", "Subway", "Domino's", "Pizza Hut", "KFC", "Popeyes", "Sonic"],
  },
  "Liquor Store / Wine Shop": {
    label: "Liquor Store / Wine Shop",
    googleTypes: ["liquor_store"],
    yelpCategories: ["beer_and_wine", "wine_bars", "breweries", "distilleries"],
    keywords: ["liquor", "wine", "spirits", "beer", "package store"],
    revenueMultiplier: 1600,
    franchiseKeywords: ["Total Wine", "BevMo", "ABC Fine Wine", "Spec's"],
  },
  "Laundromat / Dry Cleaning": {
    label: "Laundromat / Dry Cleaning",
    googleTypes: ["laundry"],
    yelpCategories: ["laundromat", "drycleaninglaundry", "laundry_services"],
    keywords: ["laundromat", "dry clean", "laundry", "wash fold"],
    revenueMultiplier: 1200,
    franchiseKeywords: ["Tide Cleaners", "Martinizing", "Lapels", "Pressed4Time", "Speed Queen"],
  },
  "Urgent Care / Walk-in Clinic": {
    label: "Urgent Care / Walk-in Clinic",
    googleTypes: ["doctor", "hospital"],
    yelpCategories: ["urgentcare", "walk_in_clinics", "medcenters"],
    keywords: ["urgent care", "walk-in", "clinic", "immediate care"],
    revenueMultiplier: 4000,
    franchiseKeywords: ["CityMD", "MedExpress", "Patient First", "AFC Urgent Care", "ConvenientMD", "GoHealth"],
  },
  "Tutoring / Learning Center": {
    label: "Tutoring / Learning Center",
    googleTypes: ["school"],
    yelpCategories: ["tutoring", "testprep", "educationservices", "specialtyschools"],
    keywords: ["tutoring", "learning center", "test prep", "education"],
    revenueMultiplier: 1800,
    franchiseKeywords: ["Kumon", "Mathnasium", "Sylvan", "Huntington", "Club Z", "Tutor Doctor", "JEI Learning"],
  },
  "Insurance Agency": {
    label: "Insurance Agency",
    googleTypes: ["insurance_agency"],
    yelpCategories: ["insurance", "auto_insurance", "homeinsurance", "lifeinsurance"],
    keywords: ["insurance", "agency", "coverage", "policy"],
    revenueMultiplier: 3200,
    franchiseKeywords: ["State Farm", "Allstate", "Farmers", "Geico", "Progressive", "Nationwide", "Liberty Mutual"],
  },
  "Real Estate Brokerage": {
    label: "Real Estate Brokerage",
    googleTypes: ["real_estate_agency"],
    yelpCategories: ["realestate", "realestateagents", "realestateservices", "propertymgmt"],
    keywords: ["real estate", "realty", "broker", "homes", "property"],
    revenueMultiplier: 4500,
    franchiseKeywords: ["RE/MAX", "Keller Williams", "Century 21", "Coldwell Banker", "eXp Realty", "Berkshire Hathaway"],
  },

  // ─── NEW: 23 NexTax industries ────────────────────────────────────────────

  "Landscaping / Lawn Care": {
    label: "Landscaping / Lawn Care",
    googleTypes: ["general_contractor"],
    yelpCategories: ["landscaping", "lawnservices", "irrigation", "treeservices", "snowremoval"],
    keywords: ["landscaping", "lawn care", "lawn service", "tree service", "irrigation", "grounds"],
    revenueMultiplier: 1400,
    franchiseKeywords: ["TruGreen", "Lawn Doctor", "Spring-Green", "U.S. LawnsPlot Pros", "BrightView", "SavATree"],
  },
  "Car Wash": {
    label: "Car Wash",
    googleTypes: ["car_wash"],
    yelpCategories: ["carwash", "auto_detailing"],
    keywords: ["car wash", "auto wash", "detailing", "express wash", "tunnel wash"],
    revenueMultiplier: 1300,
    franchiseKeywords: ["Mister Car Wash", "Wash Depot", "Zips Car Wash", "Magnolia Car Wash", "Splash Car Wash", "Quick Quack"],
  },
  "Roofing / Exterior": {
    label: "Roofing / Exterior",
    googleTypes: ["roofing_contractor", "general_contractor"],
    yelpCategories: ["roofing", "siding", "gutters"],
    keywords: ["roofing", "roof repair", "shingles", "gutter", "siding", "exterior"],
    revenueMultiplier: 2000,
    franchiseKeywords: ["USA Roofing", "Tecta America", "Nation's Roof", "CentiMark", "WeatherTech Roofing"],
  },
  "Pharmacy / Compounding": {
    label: "Pharmacy / Compounding",
    googleTypes: ["pharmacy"],
    yelpCategories: ["pharmacy", "drugstores"],
    keywords: ["pharmacy", "drug store", "compounding", "prescription", "apothecary"],
    revenueMultiplier: 3800,
    franchiseKeywords: ["CVS", "Walgreens", "Rite Aid", "Walmart Pharmacy", "Costco Pharmacy", "Good Neighbor Pharmacy"],
  },
  "Electrical Services": {
    label: "Electrical Services",
    googleTypes: ["electrician"],
    yelpCategories: ["electricians", "solar_installation", "evcharging"],
    keywords: ["electrical", "electrician", "wiring", "panel", "solar"],
    revenueMultiplier: 2600,
    franchiseKeywords: ["Mr. Electric", "Mister Sparky", "Handyman Connection", "Facility Solutions Group"],
  },
  "Home Health / Healthcare": {
    label: "Home Health / Healthcare",
    googleTypes: ["doctor", "health"],
    yelpCategories: ["homehealthcare", "hospice", "medicaltransport", "familypractice"],
    keywords: ["home health", "healthcare", "medical", "nursing", "home care"],
    revenueMultiplier: 3500,
    franchiseKeywords: ["BrightSpring", "Amedisys", "LHC Group", "AccentCare", "Encompass Health"],
  },
  "Transportation / Logistics": {
    label: "Transportation / Logistics",
    googleTypes: ["moving_company", "storage"],
    yelpCategories: ["movers", "couriers", "transport", "limos", "taxis"],
    keywords: ["transportation", "logistics", "moving", "freight", "courier", "trucking"],
    revenueMultiplier: 2000,
    franchiseKeywords: ["Two Men and a Truck", "College Hunks", "1-800-GOT-JUNK", "PODS", "U-Haul", "Budget Truck"],
  },
  "Printing / Signage": {
    label: "Printing / Signage",
    googleTypes: ["store"],
    yelpCategories: ["printing", "graphicdesign", "signmaking"],
    keywords: ["printing", "signs", "signage", "graphics", "banners", "vinyl"],
    revenueMultiplier: 1500,
    franchiseKeywords: ["Minuteman Press", "AlphaGraphics", "Signarama", "FastSigns", "Sir Speedy", "Image 360"],
  },
  "Self-Storage": {
    label: "Self-Storage",
    googleTypes: ["storage"],
    yelpCategories: ["selfstorage", "storage"],
    keywords: ["storage", "self storage", "mini storage", "climate controlled", "storage units"],
    revenueMultiplier: 2200,
    franchiseKeywords: ["Public Storage", "Extra Space Storage", "CubeSmart", "Life Storage", "U-Haul Storage", "StorageMart"],
  },
  "Painting / Coatings": {
    label: "Painting / Coatings",
    googleTypes: ["painter"],
    yelpCategories: ["painters", "epoxy_flooring"],
    keywords: ["painting", "painter", "interior painting", "exterior painting", "epoxy", "coatings"],
    revenueMultiplier: 1600,
    franchiseKeywords: ["CertaPro Painters", "Five Star Painting", "Fresh Coat", "Wow 1 Day Painting", "N-Hance"],
  },
  "Security / Alarm Services": {
    label: "Security / Alarm Services",
    googleTypes: ["locksmith", "store"],
    yelpCategories: ["security", "alarms", "homesecurity", "locksmiths"],
    keywords: ["security", "alarm", "surveillance", "cameras", "monitoring", "locksmith"],
    revenueMultiplier: 2400,
    franchiseKeywords: ["ADT", "Vivint", "SimpliSafe", "Brinks", "Guardian Alarm", "Protection 1"],
  },
  "Construction / General Contractor": {
    label: "Construction / General Contractor",
    googleTypes: ["general_contractor"],
    yelpCategories: ["general_contractors", "contractors", "buildingsupplies"],
    keywords: ["construction", "contractor", "builder", "remodeling", "renovation", "build"],
    revenueMultiplier: 2500,
    franchiseKeywords: ["DreamMaker", "Grounds Guys", "Paul Davis Restoration", "Servpro", "Rainbow International"],
  },
  "Engineering / Environmental": {
    label: "Engineering / Environmental",
    googleTypes: ["establishment"],
    yelpCategories: ["environmental_abatement", "civil_engineering"],
    keywords: ["engineering", "environmental", "civil", "structural", "consulting", "survey"],
    revenueMultiplier: 4000,
    franchiseKeywords: [],
  },
  "Grocery / Specialty Food": {
    label: "Grocery / Specialty Food",
    googleTypes: ["grocery_or_supermarket", "supermarket"],
    yelpCategories: ["grocery", "ethnic_grocery", "organicstores", "conveniencestores", "farmersmarket"],
    keywords: ["grocery", "supermarket", "food store", "market", "deli", "specialty food"],
    revenueMultiplier: 900,
    franchiseKeywords: ["Whole Foods", "Trader Joe's", "Sprouts", "Aldi", "Lidl", "Fresh Market", "Natural Grocers"],
  },
  "Property Management": {
    label: "Property Management",
    googleTypes: ["real_estate_agency"],
    yelpCategories: ["propertymgmt", "apartments", "realestate"],
    keywords: ["property management", "property manager", "rental management", "HOA", "leasing"],
    revenueMultiplier: 3500,
    franchiseKeywords: ["Real Property Management", "HomeVestors", "Associa", "FirstService Residential"],
  },
  "Remodeling / Home Improvement": {
    label: "Remodeling / Home Improvement",
    googleTypes: ["general_contractor", "home_goods_store"],
    yelpCategories: ["contractors", "kitchenremodeling", "bathroomremodeling", "flooring", "cabinetry"],
    keywords: ["remodeling", "renovation", "kitchen remodel", "bathroom remodel", "home improvement"],
    revenueMultiplier: 2200,
    franchiseKeywords: ["DreamMaker Bath & Kitchen", "Bath Fitter", "Re-Bath", "Handyman Connection", "Mr. Handyman", "Case Design"],
  },
  "Senior Care / Assisted Living": {
    label: "Senior Care / Assisted Living",
    googleTypes: ["lodging", "health"],
    yelpCategories: ["assistedliving", "seniorcenters", "homehealthcare", "hospice"],
    keywords: ["senior care", "assisted living", "memory care", "nursing home", "elder care", "senior living"],
    revenueMultiplier: 4500,
    franchiseKeywords: ["Brookdale", "Sunrise Senior Living", "Atria", "Comfort Keepers", "Right at Home", "Home Instead", "Visiting Angels"],
  },
  "Staffing / Recruiting": {
    label: "Staffing / Recruiting",
    googleTypes: ["employment_agency"],
    yelpCategories: ["employment", "staffingagencies", "careercounseling"],
    keywords: ["staffing", "recruiting", "employment agency", "temp agency", "workforce", "placement"],
    revenueMultiplier: 2800,
    franchiseKeywords: ["Robert Half", "Kelly Services", "Manpower", "Adecco", "Express Employment", "Staffmark", "Spherion", "Insight Global"],
  },
  "Veterinary Practice": {
    label: "Veterinary Practice",
    googleTypes: ["veterinary_care"],
    yelpCategories: ["veterinarians", "emergency_vets", "animalphysicaltherapy"],
    keywords: ["veterinary", "vet", "animal hospital", "animal clinic", "pet hospital"],
    revenueMultiplier: 3200,
    franchiseKeywords: ["Banfield Pet Hospital", "VCA Animal Hospitals", "BluePearl", "National Veterinary Associates", "Thrive Pet Healthcare"],
  },
  "Marketing / Advertising Agency": {
    label: "Marketing / Advertising Agency",
    googleTypes: ["establishment"],
    yelpCategories: ["advertising", "marketing", "seo", "graphicdesign", "webdesign"],
    keywords: ["marketing", "advertising", "agency", "digital marketing", "SEO", "branding"],
    revenueMultiplier: 3500,
    franchiseKeywords: ["Piranha Marketing", "WSI", "Hibu", "Scorpion", "Thrive Agency"],
  },
  "Pest Control": {
    label: "Pest Control",
    googleTypes: ["establishment"],
    yelpCategories: ["pestcontrol", "fumigation", "mosquitocontrol"],
    keywords: ["pest control", "exterminator", "termite", "rodent", "fumigation"],
    revenueMultiplier: 1800,
    franchiseKeywords: ["Orkin", "Terminix", "Rentokil", "Ehrlich", "Western Pest Services", "Arrow Exterminators", "Anticimex"],
  },
  "Ecommerce / Fulfillment": {
    label: "Ecommerce / Fulfillment",
    googleTypes: ["storage", "moving_company"],
    yelpCategories: ["fulfillmentservices", "warehousing", "shipping_centers"],
    keywords: ["fulfillment", "ecommerce", "warehouse", "shipping", "3PL", "order fulfillment"],
    revenueMultiplier: 2000,
    franchiseKeywords: ["ShipBob", "Red Stag Fulfillment", "Whiplash", "ShipMonk"],
  },
  "SaaS / Software": {
    label: "SaaS / Software",
    googleTypes: ["establishment"],
    yelpCategories: ["itservices", "softwaredev", "computerrepair"],
    keywords: ["software", "SaaS", "technology", "app", "platform", "IT services"],
    revenueMultiplier: 5000,
    franchiseKeywords: [],
  },
};

export const CATEGORIES = Object.keys(CATEGORY_MAPPINGS);
