import { CategoryMapping } from "@/types/marketview";

// ===========================================
// Business Category → API Query Mappings
// ===========================================
// Each category maps to the correct Google Places types,
// Yelp categories, and industry-specific revenue multipliers.

export const CATEGORY_MAPPINGS: Record<string, CategoryMapping> = {
  "Fitness / Gym": {
    label: "Fitness / Gym",
    googleTypes: ["gym", "health"],
    yelpCategories: ["gyms", "fitness", "boot_camps", "yoga", "pilates", "martialarts"],
    keywords: ["gym", "fitness", "crossfit", "workout", "training"],
    revenueMultiplier: 1800,
    franchiseKeywords: ["Planet Fitness", "Anytime Fitness", "Orangetheory", "F45", "Crunch", "Gold's Gym", "LA Fitness", "24 Hour", "Snap Fitness", "Burn Boot Camp"],
  },
  "Restaurant / Fast Casual": {
    label: "Restaurant / Fast Casual",
    googleTypes: ["restaurant"],
    yelpCategories: ["restaurants", "food", "fastfood", "newamerican", "tradamerican"],
    keywords: ["restaurant", "grill", "kitchen", "eatery", "dining"],
    revenueMultiplier: 1200,
    franchiseKeywords: ["Chipotle", "Panera", "Chick-fil-A", "Five Guys", "Wingstop", "Jersey Mike", "Sweetgreen", "Shake Shack", "Cava", "Noodles"],
  },
  "Coffee Shop / Cafe": {
    label: "Coffee Shop / Cafe",
    googleTypes: ["cafe"],
    yelpCategories: ["coffee", "coffeeroasteries", "coffeeshops", "bubbletea", "tea"],
    keywords: ["coffee", "cafe", "espresso", "roast", "brew"],
    revenueMultiplier: 800,
    franchiseKeywords: ["Starbucks", "Dunkin", "Peet's", "Dutch Bros", "Caribou", "Tim Hortons", "Scooter's", "Biggby"],
  },
  "Auto Repair / Service": {
    label: "Auto Repair / Service",
    googleTypes: ["car_repair"],
    yelpCategories: ["autorepair", "oilchange", "tires", "transmission_repair", "auto_detailing"],
    keywords: ["auto repair", "mechanic", "car service", "oil change", "brake"],
    revenueMultiplier: 2200,
    franchiseKeywords: ["Midas", "Jiffy Lube", "Meineke", "Maaco", "Firestone", "Pep Boys", "Valvoline", "Take 5", "Christian Brothers"],
  },
  "Dental Practice": {
    label: "Dental Practice",
    googleTypes: ["dentist"],
    yelpCategories: ["dentists", "cosmetic_dentists", "pediatric_dentists", "orthodontists", "endodontists"],
    keywords: ["dental", "dentist", "orthodont", "oral", "teeth"],
    revenueMultiplier: 3500,
    franchiseKeywords: ["Aspen Dental", "Heartland", "Pacific Dental", "Gentle Dental", "Western Dental", "Comfort Dental", "Ideal Dental"],
  },
  "Med Spa / Aesthetics": {
    label: "Med Spa / Aesthetics",
    googleTypes: ["spa", "beauty_salon"],
    yelpCategories: ["medspas", "skincare", "laser_hair_removal", "permanentmakeup"],
    keywords: ["med spa", "medspa", "aesthetics", "botox", "laser", "injectable"],
    revenueMultiplier: 2800,
    franchiseKeywords: ["Ideal Image", "LaserAway", "SkinSpirit", "Skin Laundry", "Radiance", "Sono Bello"],
  },
  "Hair Salon / Barbershop": {
    label: "Hair Salon / Barbershop",
    googleTypes: ["hair_care", "beauty_salon"],
    yelpCategories: ["hair", "hairstylists", "barbers", "blowoutservices", "hair_extensions"],
    keywords: ["salon", "barber", "hair", "cuts", "style", "color"],
    revenueMultiplier: 900,
    franchiseKeywords: ["Great Clips", "Supercuts", "Sport Clips", "Floyd's", "Roosters", "Cost Cutters", "Fantastic Sams"],
  },
  "Childcare / Daycare": {
    label: "Childcare / Daycare",
    googleTypes: ["school"],
    yelpCategories: ["childcare", "preschools", "montessori"],
    keywords: ["daycare", "childcare", "preschool", "montessori", "learning center", "child care"],
    revenueMultiplier: 2500,
    franchiseKeywords: ["KinderCare", "Bright Horizons", "Goddard School", "Primrose", "Kiddie Academy", "Children of America", "Lightbridge"],
  },
  "Pet Services / Grooming": {
    label: "Pet Services / Grooming",
    googleTypes: ["pet_store", "veterinary_care"],
    yelpCategories: ["groomer", "pet_sitting", "pet_boarding", "dog_walkers", "pet_training"],
    keywords: ["pet", "grooming", "dog", "boarding", "daycare pet"],
    revenueMultiplier: 1100,
    franchiseKeywords: ["PetSmart", "Petco", "Camp Bow Wow", "Dogtopia", "Scenthound", "Wag N' Wash"],
  },
  "Cleaning / Janitorial": {
    label: "Cleaning / Janitorial",
    googleTypes: ["home_goods_store"],
    yelpCategories: ["home_cleaning", "office_cleaning", "carpetcleaning", "window_washing"],
    keywords: ["cleaning", "janitorial", "maid", "housekeeping"],
    revenueMultiplier: 1500,
    franchiseKeywords: ["Molly Maid", "Merry Maids", "Jan-Pro", "ServiceMaster", "Chem-Dry", "Stanley Steemer", "The Maids"],
  },
  "HVAC / Plumbing": {
    label: "HVAC / Plumbing",
    googleTypes: ["plumber", "electrician"],
    yelpCategories: ["hvac", "plumbing", "heating", "air_conditioning"],
    keywords: ["hvac", "plumbing", "heating", "cooling", "air conditioning"],
    revenueMultiplier: 2800,
    franchiseKeywords: ["One Hour Heating", "Mr. Rooter", "Roto-Rooter", "Benjamin Franklin", "Aire Serv", "ARS Rescue Rooter"],
  },
  "Accounting / Tax Services": {
    label: "Accounting / Tax Services",
    googleTypes: ["accounting"],
    yelpCategories: ["accountants", "tax_services", "bookkeepers", "payroll_services"],
    keywords: ["accounting", "tax", "CPA", "bookkeeping", "payroll"],
    revenueMultiplier: 3000,
    franchiseKeywords: ["H&R Block", "Jackson Hewitt", "Liberty Tax", "Padgett Business Services"],
  },
  "Physical Therapy / Chiropractic": {
    label: "Physical Therapy / Chiropractic",
    googleTypes: ["physiotherapist", "doctor"],
    yelpCategories: ["physicaltherapy", "chiropractors", "sports_medicine", "acupuncture"],
    keywords: ["physical therapy", "chiropract", "rehab", "sports medicine"],
    revenueMultiplier: 2400,
    franchiseKeywords: ["ATI Physical Therapy", "CORA", "Athletico", "US Physical Therapy", "The Joint"],
  },
  "Quick Service Restaurant (QSR)": {
    label: "Quick Service Restaurant (QSR)",
    googleTypes: ["restaurant", "meal_takeaway"],
    yelpCategories: ["hotdogs", "burgers", "pizza", "sandwiches", "chicken_wings", "mexican"],
    keywords: ["fast food", "drive thru", "quick service", "takeout"],
    revenueMultiplier: 1400,
    franchiseKeywords: ["McDonald's", "Burger King", "Wendy's", "Taco Bell", "Subway", "Domino's", "Pizza Hut", "KFC", "Popeyes", "Sonic"],
  },
  "Liquor Store / Wine Shop": {
    label: "Liquor Store / Wine Shop",
    googleTypes: ["liquor_store"],
    yelpCategories: ["beer_and_wine", "wine_bars", "breweries", "distilleries"],
    keywords: ["liquor", "wine", "spirits", "beer", "package store"],
    revenueMultiplier: 1600,
    franchiseKeywords: ["Total Wine", "BevMo", "ABC Fine Wine", "Spec's"],
  },
  "Laundromat / Dry Cleaning": {
    label: "Laundromat / Dry Cleaning",
    googleTypes: ["laundry"],
    yelpCategories: ["laundromat", "drycleaninglaundry", "laundry_services"],
    keywords: ["laundromat", "dry clean", "laundry", "wash fold"],
    revenueMultiplier: 1200,
    franchiseKeywords: ["Tide Cleaners", "Martinizing", "Lapels", "Pressed4Time", "Speed Queen"],
  },
  "Urgent Care / Walk-in Clinic": {
    label: "Urgent Care / Walk-in Clinic",
    googleTypes: ["doctor", "hospital"],
    yelpCategories: ["urgentcare", "walk_in_clinics", "medcenters"],
    keywords: ["urgent care", "walk-in", "clinic", "immediate care"],
    revenueMultiplier: 4000,
    franchiseKeywords: ["CityMD", "MedExpress", "Patient First", "AFC Urgent Care", "ConvenientMD", "GoHealth"],
  },
  "Tutoring / Learning Center": {
    label: "Tutoring / Learning Center",
    googleTypes: ["school"],
    yelpCategories: ["tutoring", "testprep", "educationservices", "specialtyschools"],
    keywords: ["tutoring", "learning center", "test prep", "education"],
    revenueMultiplier: 1800,
    franchiseKeywords: ["Kumon", "Mathnasium", "Sylvan", "Huntington", "Club Z", "Tutor Doctor", "JEI Learning"],
  },
  "Insurance Agency": {
    label: "Insurance Agency",
    googleTypes: ["insurance_agency"],
    yelpCategories: ["insurance", "auto_insurance", "homeinsurance", "lifeinsurance"],
    keywords: ["insurance", "agency", "coverage", "policy"],
    revenueMultiplier: 3200,
    franchiseKeywords: ["State Farm", "Allstate", "Farmers", "Geico", "Progressive", "Nationwide", "Liberty Mutual"],
  },
  "Real Estate Brokerage": {
    label: "Real Estate Brokerage",
    googleTypes: ["real_estate_agency"],
    yelpCategories: ["realestate", "realestateagents", "realestateservices", "propertymgmt"],
    keywords: ["real estate", "realty", "broker", "homes", "property"],
    revenueMultiplier: 4500,
    franchiseKeywords: ["RE/MAX", "Keller Williams", "Century 21", "Coldwell Banker", "eXp Realty", "Berkshire Hathaway"],
  },
};

export const CATEGORIES = Object.keys(CATEGORY_MAPPINGS);
